### ISSUE TITLE
List of own samples

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-frontend#53]
- Headline so that it does not disappear behind the side menu (center?)
- Search field below headline
- "Sample Type Name" -> "Sample Type"
- remove URL column
- Add list of descriptors column (can you use the tags there?)
- Add new sample is a button. Either make the background more visible

**Comment by Anubhav2201** [comment]
Commit : 1193cba7bdf0ffdf5f7bcf7bc554786a80ada67f
54e347af4087da18063e53b4595fe6ed20453b84
Changes still to make : 
- Headline so that it does not disappear behind the side menu (center?)
- Add list of descriptors column (can you use the tags there?)

Note : For --Add list of descriptors column (can you use the tags there?)
getsample ws is not providing sample descriptor information

**Comment by Anubhav2201** [comment]
For Remaining Changes: 
- Headline so that it does not disappear behind the side menu (center?)
Opened a new issue : https://github.com/ReneRanzinger/IFEDS-frontend/issues/65

- Add list of descriptors column (can you use the tags there?)
Opened a new issue : https://github.com/ReneRanzinger/IFEDS-frontend/issues/66
